import { bangldeshMenuQuery, kenyaMenuQuery, mainMenuQuery} from "./menuQuery";
import { pageDataQuery} from "./pageDataQuery.js";
import {    slugsQuery} from "./slugsQuery";
import {    blogQuery} from "./blogQuery";
import {    membersQuery} from "./membersQuery";
import {    allProjectQuery} from "./allProjectQuery";
import {    singleProjectQuery} from "./singleProjectQuery";
import {    singleBlogQuery} from "./singleBlogQuery";
import {    allResourceQuery} from "./allResourceQuery";
export {mainMenuQuery, pageDataQuery, slugsQuery, blogQuery, membersQuery, allProjectQuery, kenyaMenuQuery, bangldeshMenuQuery, singleProjectQuery, singleBlogQuery, allResourceQuery};