import { Poppins } from "next/font/google";
import "./globals.css";
import FooterSection from "@/components/footer/FooterSection";
import HeaderSection from "@/components/HeaderSection.jsx/HeaderSection";
import AOSWrapper from "@/utils/AOSWrapper";
import { ReactLenis } from "@/utils/lenis";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "600"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${poppins.variable} relative font-poppins antialiased`}
        >
          <AOSWrapper>
            <HeaderSection
              logoLink="/saf-logo.png"
              buttonDetails={{ title: "Contact Us", link: "/" }}
              navigations={[
                {
                  id: crypto.randomUUID(),
                  groupName: "About Us",
                  childNavigations: [
                    {
                      id: crypto.randomUUID(),
                      title: "Who we are",
                      link: "/who-we-are",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Our leadership",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Our history",
                      link: "/",
                    },
                  ],
                },
                {
                  id: crypto.randomUUID(),
                  groupName: "Our Work",
                  childNavigations: [
                    {
                      id: crypto.randomUUID(),
                      title: "Thematic Areas",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Projects & Programs",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Donors and Partners",
                      link: "/",
                    },
                  ],
                },
                {
                  id: crypto.randomUUID(),
                  groupName: "Global Presence",
                  childNavigations: [
                    {
                      id: crypto.randomUUID(),
                      title: "Switzerland (HQ)",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Bangladesh",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "India",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Kenya",
                      link: "/",
                    },
                  ],
                },
                {
                  id: crypto.randomUUID(),
                  groupName: "Our Impact",
                  childNavigations: [
                    {
                      id: crypto.randomUUID(),
                      title: "Reports & Publications",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Impact Stories",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Blogs & Articles | News",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Photo Gallery",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Video Gallery",
                      link: "/",
                    },
                  ],
                },
                {
                  id: crypto.randomUUID(),
                  groupName: "Get Involved",
                  childNavigations: [
                    {
                      id: crypto.randomUUID(),
                      title: "Our Culture",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Career",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Consultancy & EOI",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Contact Us",
                      link: "/",
                    },
                  ],
                },
              ]}
            />
            {children}
            <FooterSection
              footerLogo="/saf-logo.svg"
              footerDonation={{
                label: "You Can Help—Contribute Today!",
                btnDetails: {
                  title: "Donate",
                  link: "/",
                },
              }}
              navigations={[
                {
                  id: crypto.randomUUID(),
                  groupName: "About Us",
                  childNavigations: [
                    {
                      id: crypto.randomUUID(),
                      title: "Who we are",
                      link: "/who-we-are",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Our leadership",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Our history",
                      link: "/",
                    },
                  ],
                },
                {
                  id: crypto.randomUUID(),
                  groupName: "Our Work",
                  childNavigations: [
                    {
                      id: crypto.randomUUID(),
                      title: "Thematic Areas",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Projects & Programs",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Donors and Partners",
                      link: "/",
                    },
                  ],
                },
                {
                  id: crypto.randomUUID(),
                  groupName: "Global Presence",
                  childNavigations: [
                    {
                      id: crypto.randomUUID(),
                      title: "Switzerland (HQ)",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Bangladesh",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "India",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Kenya",
                      link: "/",
                    },
                  ],
                },
                {
                  id: crypto.randomUUID(),
                  groupName: "Our Impact",
                  childNavigations: [
                    {
                      id: crypto.randomUUID(),
                      title: "Reports & Publications",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Impact Stories",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Blogs & Articles | Press | News",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Photo Gallery",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Video Gallery",
                      link: "/",
                    },
                  ],
                },
                {
                  id: crypto.randomUUID(),
                  groupName: "Get Involved",
                  childNavigations: [
                    {
                      id: crypto.randomUUID(),
                      title: "Our Culture",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Career",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Consultancy & EOI",
                      link: "/",
                    },
                    {
                      id: crypto.randomUUID(),
                      title: "Contact Us",
                      link: "/",
                    },
                  ],
                },
              ]}
              footerBottom={{
                copyRightText: "© 2024 Sustainable Agriculture Foundation",
                navigations: [
                  {
                    id: crypto.randomUUID(),
                    title: "Privacy Notice",
                    link: "/",
                  },
                  {
                    id: crypto.randomUUID(),
                    title: "Tearms of Use",
                    link: "/",
                  },
                ],
              }}
            />
          </AOSWrapper>
        </body>
      </ReactLenis>
    </html>
  );
}
